[book]
authors = [
  "Mateusz Urbanek"
]
language = "en"
src = "src"
title = "OpenCrusade"

[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/shanduur/OpenCrusade/tree/main"
edit-url-template = "https://github.com/shanduur/OpenCrusade/edit/main/{path}"
hash-files = true
additional-js = ["src/_js/mermaid.min.js", "src/_js/mermaid-init.js"]

[output.html.fold]
enable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.github-authors]
command = "mdbook-github-authors"
