name: Repository malware scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    scan:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: dell/common-github-actions/malware-scanner@main
          with:
            directories: .
            options: --recursive --infected
